name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.repository != 'elixir-wallaby/workflow-test')

    steps:
      - name: Did I run?
        run: |
          echo "Did I run?"
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "ref: ${{ github.ref}}"
          echo "head_ref: ${{ github.head_ref}}"

  control:
    name: Control
    runs-on: ubuntu-latest

    steps:
      - name: I will always run
        run: |
          echo "I always run!"
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "ref: ${{ github.ref}}"
          echo "head_ref: ${{ github.head_ref}}"
